### ISSUE TITLE
Build failed (product/archive)

### ISSUE THREAD

**Issue by mybookinglife** [vasilich6107/react-native-liqpay#2]
Hello!
Help me solve the problem.
When I build an application through product/build - that's all right
But when i try to build the app for production (product/archive), I get an error
I'm clear cache, reinstall node_modules - does not work

bitcode bundle could not be generated because '/Users/chaos/Library/Developer/Xcode/DerivedData/HealthyWay-gyyuadejzrqrczfsccroybbyypnl/Build/Intermediates.noindex/ArchiveIntermediates/HealthyWay/BuildProductsPath/Release-iphoneos/libRNLiqpay.a(libLiqpayMob.a-armv7-master.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/chaos/Library/Developer/Xcode/DerivedData/HealthyWay-gyyuadejzrqrczfsccroybbyypnl/Build/Intermediates.noindex/ArchiveIntermediates/HealthyWay/BuildProductsPath/Release-iphoneos/libRNLiqpay.a' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vasilich6107** [comment]
Hi.
Try to disable ENABLE_BITCODE flag in build settings tab if your app do not need to support bitcode.

**Comment by mybookinglife** [comment]
Hi.
Thank you!!! 
disable ENABLE_BITCODE - it helped for me
