### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by nikolas77380** [vasilich6107/react-native-liqpay#3]
Hello! thank you for this module. I have issue with define error - it worked fine until update of react, react-native, babel-preset-react-native  - now when I click to checkout button it opens web view but with error object - {"result": "error", "description": "internal_error"}

**Comment by vasilich6107** [comment]
Hi! What versions did you use?

**Comment by vasilich6107** [comment]
Just updated to the latest RN 0.56 - everything works fine.
Please recheck. May be it was PrivatBank internal issues.

**Comment by nikolas77380** [comment]
Hi, recheck after one day and now it works - sorry for interrupt and thank you for your attention!
