### ISSUE TITLE
don't display component

### ISSUE THREAD

**Issue by provodar** [vasilich6107/react-native-liqpay#4]
Hello. I have issue with display component. 

In Android when I click to checkout button, nothing opens.
When I put LiqpayCheckout into Modal, it just freezes and does not close.

In iOS checkout work normally until press "cancel" or "pay" after that Modal freezes and does not close too. Without Modal - blank screen.

p.s. I made only 2-5 steps of Android manual installation. After 1 step i got an error: package com.reactlibrary does not exist. Is the mistake in readme?

**Comment by vasilich6107** [comment]
Did you run `react-native link react-native-liqpay` before any platform specific actions?

**Comment by provodar** [comment]
Yes, i did. 

After that i found
"import com.vasilich6107.rnliqpay.RNLiqpayPackage" and "new RNLiqpayPackage()" in MainApplication.java

**Comment by vasilich6107** [comment]
Can you provide(repo on github) a boilerplate project that reproduces error you talking about?

**Comment by provodar** [comment]
Sure
https://github.com/provodar/temp

**Comment by vasilich6107** [comment]
`npm i`
`react-native run-ios`
And here what I got - https://tppr.me/Nea20

Let's start from the scratch.
Create an empty project and add `react-native-liqpay` to it without any other libraries included.
Add a button and try to launch the liqpay if you'll have any errors post the project and I will take a look.
But only the empty project and one lib`react-native-liqpay`)

**Comment by vasilich6107** [comment]
I've added an example project to current repo and updated  README(android section 6 and 7) file to match the latest react-native version. Hope it will help you)

**Comment by aevpraid** [comment]
I have the same problem =(

It manifests itself if remote debug turn-off
