### ISSUE TITLE
RNLiqpay was not found in the UIManager

### ISSUE THREAD

**Issue by kohrimenko** [vasilich6107/react-native-liqpay#5]
Полный текст ошибки (Android)
Invariant Violation: requireNativeComponent: "RNLiqpay" was not found in the UIManager
This error is located at:
in RNLiqpay (at index.js:14)
in LiqpayCheckout (at App.js:35)
..

react-native -v
react-native-cli: 2.0.1
react-native: 0.56.0

compileSdkVersion 26
buildToolsVersion '26.0.3'
minSdkVersion 16
targetSdkVersion 26

**Comment by vasilich6107** [comment]
Hi. It seems that you missed some installation step. Did you try to launch an example project from this repo?

**Comment by kohrimenko** [comment]
An old version of node was installed. Now it's work fine with v8.3. Thank you!
