### ISSUE TITLE
Безопасность clientkey и privatekey

### ISSUE THREAD

**Issue by taras-vlasenko** [vasilich6107/react-native-liqpay#8]
У меня вопрос по поводу безопасности этих ключей, ведь apk файл можно переименовать в zip и найти эти ключи (даже с обфусцированными именами переменных) и, по сути, у клиента находится секретная информация. Как вариант, можно реализовать оплату как в web версии, с генерацией формы с подписью этими ключами, но уже на стороне сервера и клиенту просто отправить формочку, по которой нужно перейти. Может, у Вас есть какие-нибудь лучшие решения? Спасибо

**Comment by vasilich6107** [comment]
ПрайватКей не должен появляться на клиенте)
