### ISSUE TITLE
RNLiqpay was not found in the UIManager

### ISSUE THREAD

**Issue by devs9** [vasilich6107/react-native-liqpay#9]
выкидывает RNLiqpay was not found in the UIManager
 Запускается только example

**Comment by oxyii** [comment]
@devs9 Комьюнити - сила! Я, в принципе, понимал, что проблема именно в podspec файле, но опыта именно с огрызком мало. Спасибо, @SergeyG за правки, но пред-скомпиллированный LiqpayMob всё равно подключать надо было вручную. Я добавил его в podspec. Можно ставить этот [форк](https://github.com/oxyii/react-native-liqpay).

```bash
yarn add github:oxyii/react-native-liqpay
```
Автолинкинг (RN >= 0.60) работает. Просто `pod install` после установки самого пакета.

**Comment by oxyii** [comment]
До выхода релиза от @vasilich6107 старше `0.3.2` можем ставить эту либу напрямую из репы
```bash
yarn add github:vasilich6107/react-native-liqpay
```

**Comment by vasilich6107** [comment]
Готово)
